INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Blood bag', 'Treatment Equipment', 520, 'Choroid plexectomy', '30-Aug-2046');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Braces', 'Diagnostic Equipment', 127, 'Laparoscopy', '14-May-2028');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Rubber gloves', 'Treatment Equipment', 198, 'Facial bone biopsy', '05-Mar-2022');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Ambulance', 'Medical Laboratory Equipment', 29, 'Remov mediastinal drain', '27-Sep-2033');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('First aid kit', 'Diagnostic Equipment', 125, 'Toxicology-eye', '22-Dec-2033');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Microscope', 'Durable Medical Equipment', 170, 'Opn abltn liver les/tiss', '07-Sep-2028');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Crutch', 'Treatment Equipment', 271, 'Cholera vaccination', '26-Oct-2033');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Walker', 'Diagnostic Equipment', 391, 'Debridement of nail', '26-Jul-2047');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Manual Wheelchair', 'Diagnostic Equipment', 48, 'Skull plate removal', '05-Oct-2049');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Electric Wheelchair', 'Diagnostic Equipment', 528, 'Open valvuloplasty NOS', '03-Oct-2034');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Cane', 'Life Support Equipment', 807, 'Exc wound debridement', '24-Apr-2022');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Scissors', 'Durable Medical Equipment', 104, 'Total elbow replacement', '17-Oct-2024');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Scalpel', 'Treatment Equipment', 156, 'Infus drotrecogin alfa', '14-Jan-2028');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Syringe', 'Life Support Equipment', 664, 'Spleen diagnost proc NEC', '23-Nov-2039');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Stethoscope', 'Diagnostic Equipment', 748, 'Tot abd colectmy NEC/NOS', '08-Apr-2050');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Pipette', 'Life Support Equipment', 402, 'Tm manipulation NEC', '13-Apr-2038');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Tooth brush', 'Medical Laboratory Equipment', 529, 'Esophageal dilation', '16-Jul-2037');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Thermometer', 'Life Support Equipment', 88, 'Venous cutdown', '26-Dec-2031');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Dental pick', 'Medical Laboratory Equipment', 289, 'Gastric lavage', '10-Oct-2023');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Saline bag', 'Treatment Equipment', 928, 'Oth plastic repair palat', '21-Jun-2039');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Glasses', 'Treatment Equipment', 89, 'Open large bowel biopsy', '14-Aug-2024');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Sunglasses', 'Diagnostic Equipment', 239, 'Chest cage sequestrec', '21-Sep-2027');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Dumbbells', 'Medical Laboratory Equipment', 206, 'Removal fb/dev from skin', '06-Feb-2036');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Stretcher', 'Treatment Equipment', 977, 'Repair ob lac rect/anus', '20-Mar-2021');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Surgical mask', 'Medical Laboratory Equipment', 499, 'Sphenoidotomy', '15-Sep-2047');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Face mask', 'Treatment Equipment', 473, 'Choledochoplasty', '01-Oct-2025');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Tape', 'Diagnostic Equipment', 352, 'Perc ins extracran stent', '27-Dec-2041');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Bandage', 'Life Support Equipment', 111, 'Resrf hip,part-acetablum', '07-Feb-2029');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Hospital beds', 'Durable Medical Equipment', 326, 'Urterost/urete cth irrig', '04-Jun-2040');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Walkers', 'Life Support Equipment', 74, 'Fus/refus 9 vertebrae', '21-Nov-2028');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Traction equipment', 'Durable Medical Equipment', 30, 'Interat ven retrn transp', '29-Apr-2039');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Pressure mattresses', 'Medical Laboratory Equipment', 523, 'Exc pituit les-transphen', '30-Jun-2027');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Insulin pumps', 'Diagnostic Equipment', 488, 'Gracilis musc transplan', '30-Aug-2046');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Breast pumps', 'Durable Medical Equipment', 528, 'Int fixation-chest cage', '27-Apr-2050');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Nebulizers', 'Treatment Equipment', 267, 'Rem extratub ectop preg', '28-Dec-2027');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Patient Lifts', 'Diagnostic Equipment', 553, 'Partial hip replacement', '18-Feb-2048');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Bili lights and blankets', 'Treatment Equipment', 629, 'Trnsapcl repl pulm valve', '04-Mar-2044');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Kidney machines', 'Diagnostic Equipment', 336, 'Remove int penile prosth', '10-Oct-2037');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Stationary or portable oxygen tanks', 'Treatment Equipment', 20, 'Implant ureteral stimul', '24-Jan-2039');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Oxygen Concentrators Ventilators', 'Treatment Equipment', 213, 'Vasc shunt and bypass NEC', '09-Oct-2033');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Infusion Pumps', 'Durable Medical Equipment', 651, 'Repl/rep thr unt tot hrt', '24-Aug-2047');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('LASIK Surgical machines', 'Diagnostic Equipment', 130, 'Loc exc bony palate les', '28-Jun-2039');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Medical Lasers', 'Medical Laboratory Equipment', 647, 'Kidney transplant NEC', '23-Jun-2047');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Diagnostic scopes', 'Durable Medical Equipment', 272, 'Muscle thermography', '04-Mar-2034');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Surgical caps', 'Durable Medical Equipment', 791, 'Rad node dissection NEC', '10-May-2024');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Surgical gowns', 'Durable Medical Equipment', 805, 'Lam keratplast w autgrft', '08-May-2042');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Surgical gloves', 'Life Support Equipment', 659, 'Lap adhesiolys ova/tube', '07-May-2048');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Surgical glasses', 'Life Support Equipment', 643, 'Incise cerebral meninges', '11-Jan-2041');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Gauze', 'Durable Medical Equipment', 903, 'App ext fix dev-monoplan', '04-May-2030');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Drapes', 'Life Support Equipment', 248, 'Stapes mobilization', '23-Jul-2046');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Heart-lung machines', 'Medical Laboratory Equipment', 653, 'Stern esophag anast NEC', '27-Jun-2026');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Medical ventilators', 'Medical Laboratory Equipment', 259, 'Sm bowel stoma revision', '02-May-2043');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Dialysis machine', 'Diagnostic Equipment', 236, 'Platelet transfusion', '04-Jan-2047');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Incubators', 'Medical Laboratory Equipment', 727, 'Wrist arthroscopy', '24-Nov-2024');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Blood gas analyzers', 'Medical Laboratory Equipment', 544, 'Amputation of cervix', '08-Feb-2048');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Chemistry analyzers', 'Durable Medical Equipment', 622, 'Extraperitoneal c-sect', '10-Feb-2029');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Blood collection supplies', 'Life Support Equipment', 925, 'Other gastrostomy', '02-Sep-2034');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Electrolyte analyzers', 'Life Support Equipment', 945, 'Incis vulva/perineum NEC', '10-Oct-2043');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Differential counters', 'Medical Laboratory Equipment', 919, 'Lap incid appendectomy', '30-May-2024');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Drug testing analyzers', 'Treatment Equipment', 393, 'Pancreatic homotransplan', '21-Oct-2037');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Coagulation analyzers', 'Medical Laboratory Equipment', 28, 'Sympathetic nerve biopsy', '15-Oct-2024');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Hematology analyzers', 'Life Support Equipment', 429, 'Cut and prep pedicle graft', '13-Mar-2030');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Urinalysis analyzers', 'Durable Medical Equipment', 972, 'Hemorrhoid reduction', '27-Apr-2044');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Microbiological systems', 'Durable Medical Equipment', 247, 'Partial cystectomy', '12-Oct-2023');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Medical imaging machines', 'Medical Laboratory Equipment', 247, 'Saliv lesion excis NEC', '12-May-2040');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Stethoscopes', 'Treatment Equipment', 985, 'Breast dx procedure NEC', '11-May-2031');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Dopplers', 'Durable Medical Equipment', 421, 'Oth lo vision aid dispen', '07-Jan-2029');
INSERT INTO ITEMS (name, category, quantity, description, date_expired) VALUES ('Pulse oximetry', 'Life Support Equipment', 421, 'Ventricl shunt-thorax', '14-May-2043');
