SELECT * FROM Staff;

CREATE OR REPLACE VIEW Full_Details_Staff AS
SELECT * FROM Staff;

INSERT INTO Full_Details_Staff
VALUES(7777, 'Gavin B', '27-JUL-20', '10_JAN-00', 1001);

CREATE OR REPLACE VIEW Full_Details_Staff AS
SELECT * FROM Staff
WHERE Salary > 1000
WITH CHECK OPTION CONSTRAINT check_condition;

SELECT * FROM Full_Details_Staff;

CREATE USER G01N01 IDENTIFIED BY password DEFAULT TABLESPACE USERS;
CREATE USER G01N02 IDENTIFIED BY password DEFAULT TABLESPACE USERS;
GRANT RESOURCE, CREATE SESSION TO G01N01;
GRANT RESOURCE, CREATE SESSION TO G01N02;

GRANT SELECT / UPDATE(Staff_name) / DELETE / INSERT / ALL PRIVILEGES
ON STAFF
TO G01N01 / PUBLIC
WITH GRANT OPTION;

GRANT SELECT ON Staff TO G01N01 WITH GRANT OPTION;
SELECT * FROM marcus.Staff;
GRANT SELECT ON marcus.Staff TO G01N02;

REVOKE SELECT ON Staff FROM G01N01;

DROP USER G01N01 CASCADE;
DROP USER G01N02 CASCADE;